{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_login_page", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_change_password", "rerun": "0"}}, "suite_name": "tests/test_generic_ui.py"}, "1": {"suite_name": "tests/auth/test_roles_controller.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_get_iceauth_api_roles_getallroles", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-SysAdmin]", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-CFGTEMPLATE]", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-System]", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-AudAdmin]", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-LookupAdmin]", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-CFGADMIN]", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-AuthAdmin]", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-AppAdmin]", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-CfgImporter]", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-AuthUser]", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user0-MaintainAccReg]", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-SysAdmin]", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-CFGTEMPLATE]", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-System]", "rerun": "0"}, "15": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-AudAdmin]", "rerun": "0"}, "16": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-LookupAdmin]", "rerun": "0"}, "17": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-CFGADMIN]", "rerun": "0"}, "18": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-AuthAdmin]", "rerun": "0"}, "19": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-AppAdmin]", "rerun": "0"}, "20": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-CfgImporter]", "rerun": "0"}, "21": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-AuthUser]", "rerun": "0"}, "22": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_roles_addusertorole[user1-MaintainAccReg]", "rerun": "0"}, "23": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-SysAdmin]", "rerun": "0"}, "24": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-CFGTEMPLATE]", "rerun": "0"}, "25": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-System]", "rerun": "0"}, "26": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-AudAdmin]", "rerun": "0"}, "27": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-LookupAdmin]", "rerun": "0"}, "28": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-CFGADMIN]", "rerun": "0"}, "29": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-AuthAdmin]", "rerun": "0"}, "30": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-AppAdmin]", "rerun": "0"}, "31": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-CfgImporter]", "rerun": "0"}, "32": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-AuthUser]", "rerun": "0"}, "33": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user0-MaintainAccReg]", "rerun": "0"}, "34": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-SysAdmin]", "rerun": "0"}, "35": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-CFGTEMPLATE]", "rerun": "0"}, "36": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-System]", "rerun": "0"}, "37": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-AudAdmin]", "rerun": "0"}, "38": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-LookupAdmin]", "rerun": "0"}, "39": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-CFGADMIN]", "rerun": "0"}, "40": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-AuthAdmin]", "rerun": "0"}, "41": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-AppAdmin]", "rerun": "0"}, "42": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-CfgImporter]", "rerun": "0"}, "43": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-AuthUser]", "rerun": "0"}, "44": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_roles_removeuserfromrole[user1-MaintainAccReg]", "rerun": "0"}}, "status": {"total_pass": 45, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "2": {"suite_name": "tests/auth/test_token_controller.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_oauth_token", "rerun": "0"}}, "status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "3": {"suite_name": "tests/auth/test_token_controller_two.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_json", "rerun": "0"}}, "status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "4": {"suite_name": "tests/auth/test_user_controller.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_get_iceauth_api_users_getusersforagency", "rerun": "0"}}, "status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "5": {"suite_name": "tests/auth/test_user_controller_two.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_get_iceauth_api_v2_users[user0]", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_get_iceauth_api_v2_users[user1]", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_json", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_get_iceauth_api_v2_users_json_getusersforagency", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_activate[user0]", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_activate[user1]", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_password_update[user0]", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_password_update[user1]", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_json_password_reset[user0]", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_json_password_reset[user1]", "rerun": "0"}, "10": {"status": "FAIL", "message": "   TypeError: list indices must be integers or slices, not str\n", "test_name": "test_delete_iceauth_api_v2_users[user0]", "rerun": "0"}, "11": {"status": "FAIL", "message": "   TypeError: list indices must be integers or slices, not str\n", "test_name": "test_delete_iceauth_api_v2_users[user1]", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_deactivate[user0]", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_post_iceauth_api_v2_users_deactivate[user1]", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_v2_users_json[user0]", "rerun": "0"}, "15": {"status": "PASS", "message": "", "test_name": "test_delete_iceauth_api_v2_users_json[user1]", "rerun": "0"}, "16": {"status": "PASS", "message": "", "test_name": "test_get_iceauth_api_v2_users_json[user0]", "rerun": "0"}, "17": {"status": "PASS", "message": "", "test_name": "test_get_iceauth_api_v2_users_json[user1]", "rerun": "0"}, "18": {"status": "PASS", "message": "", "test_name": "test_put_iceauth_api_v2_users_json[user0]", "rerun": "0"}, "19": {"status": "FAIL", "message": "           TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1653CD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1653CD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1653CD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))\n", "test_name": "test_put_iceauth_api_v2_users_json[user1]", "rerun": "0"}, "20": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1AAF640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1AAF640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1AAF640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_get_iceauth_api_v2_users_json_anonymous[user0]", "rerun": "0"}, "21": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C17E7400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C17E7400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C17E7400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_get_iceauth_api_v2_users_json_anonymous[user1]", "rerun": "0"}, "22": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1A1B130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1A1B130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1A1B130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_json_anonymous[user0]", "rerun": "0"}, "23": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1BFA370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1BFA370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1BFA370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_json_anonymous[user1]", "rerun": "0"}, "24": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1CAAE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1CAAE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1CAAE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_json_activate[user0]", "rerun": "0"}, "25": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1CA2370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1CA2370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1CA2370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_json_activate[user1]", "rerun": "0"}, "26": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1CBFE80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1CBFE80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1CBFE80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_get_iceauth_api_v2_users_json_find[user0]", "rerun": "0"}, "27": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C195D100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C195D100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C195D100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_get_iceauth_api_v2_users_json_find[user1]", "rerun": "0"}, "28": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C19409A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C19409A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C19409A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_json_lock[user0]", "rerun": "0"}, "29": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1B19BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1B19BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1B19BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_json_lock[user1]", "rerun": "0"}, "30": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1D77700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1D77700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1D77700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_json_password_resetrequest[user0]", "rerun": "0"}, "31": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1BDC9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1BDC9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1BDC9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_json_password_resetrequest[user1]", "rerun": "0"}, "32": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C18FB2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C18FB2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C18FB2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_get_iceauth_api_v2_users_userroles[user0]", "rerun": "0"}, "33": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1DB47F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1DB47F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1DB47F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_get_iceauth_api_v2_users_userroles[user1]", "rerun": "0"}, "34": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1E31280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1E31280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1E31280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_get_iceauth_api_v2_users_search[user0]", "rerun": "0"}, "35": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1BCC490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1BCC490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1BCC490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_get_iceauth_api_v2_users_search[user1]", "rerun": "0"}, "36": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1E73EB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1E73EB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1E73EB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_lock[user0]", "rerun": "0"}, "37": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168C1B51430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1B51430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='dev.spsi.co.za', port=80): Max retries exceeded with url: /ICEAUTH/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168C1B51430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "test_name": "test_post_iceauth_api_v2_users_lock[user1]", "rerun": "0"}}, "status": {"total_pass": 17, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 21, "total_error": 0}}}}, "date": "March 30, 2023", "start_time": 1680199517.4483948, "total_suite": 6, "status": "FAIL", "status_list": {"pass": "67", "fail": "21", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "88"}